### ISSUE TITLE
Error importing components from inside React root component

### ISSUE THREAD

**Issue by cacods** [frictionlessdata/components#10]
# Overview

Trying to import frictionless-components gives error at console's browser.
```
ReferenceError: exports is not defined
    at Module../node_modules/frictionless-components/lib/components/Workflow.js (Workflow.js:61)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/frictionless-components/lib/index.js (index.js:34)
    at __webpack_require__ (bootstrap:19)
    at Module../app/javascript/containers/UploadFiles.js (.*$:24)
    at __webpack_require__ (bootstrap:19)
    at webpackContext (.*$:9)
    at fromRequireContext.js:13
    at Object.getConstructor (fromRequireContextWithGlobalFallback.js:15)
    at Object.mountComponents (index.js:89)
```
This error occurs in line 24 at the Workflow.js file:

`Object.defineProperty(exports, "__esModule", { value: true });`

The import statement is at the root React component, created at the top of [react-rails](https://github.com/reactjs/react-rails), in a rails application.

Please let me know if more info is required.

---
Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@cacods 
Is the client code public? Can you please link? And please provide the code you mean but `trying to import`.

In general, this import/export stuff is really annoying. I just fixed it for the from CDN use but now it comes from another use case

**Comment by cacods** [comment]
I don't know it it can help @roll but I got the package working (with some css/javascript mess) with the following changes:

1. In lib/index.js: commented out line 17 for exporting Workflow related stuff.
`// __exportStar(require("./components/Workflow"), exports);`

2. Change format of importing frictionless-components:
```
import 'frictionless-components/lib/styles';
import * as frictionlessComponents from 'frictionless-components';
```
3. add top level json object (**report**) for the json report validation, like

```
const ReportTest = {
    "report": {
        "version": "4.6.0",
        "time": 0.022,
        "errors": [],
        "tasks": [
            {
        //...
}
```

4. Finally calling the component:
```
const testReport = document.getElementById('test_report');
frictionlessComponents.render(frictionlessComponents.Report, reportTest, testReport);
```

**Comment by roll** [comment]
@cacods 
Can you please try exporting `render` and `Report` directly from their files `lib/render` and `lib/components/Report`?

**Comment by roll** [comment]
Thanks. Can you add a screenshot of the visual problems?

**Comment by cacods** [comment]
Of course. This is an image of the rendered output, with the two issues more pronounced pointed out: collapse/expand not working and the table with the problems indicated visually.

![frictionless_components_style_issues](https://user-images.githubusercontent.com/75754641/120358980-87fd0880-c2dd-11eb-8ef0-130fa46a3179.png)

**Comment by roll** [comment]
Do you have bootstrapped's CSS added?

**Comment by cacods** [comment]
Do you mean https://getbootstrap.com/docs/3.4/css? No I don't think so.

**Comment by roll** [comment]
https://github.com/frictionlessdata/goodtables-ui#requirements

It has been migrated to this lib docs yet

**Comment by cacods** [comment]
Oh I see. I will talk to Dryad guys about installing Bootstrap. Thanks @roll.

**Comment by cacods** [comment]
Added Bootstrap 4 official CDN and it works like a charm. Thanks!

**Comment by roll** [comment]
I tested import with a fresh installation and both from below works:

```javascript
const frictionless = require('frictionless-components')
const frictionless await import('frictionless-components')
```
```
{
  Report: [Getter],
  ReportError: [Getter],
  ReportTable: [Getter],
  ReportTask: [Getter],
  getReportErrors: [Getter],
  Workflow: [Getter],
  render: [Getter]
}
```

Probably, it was a problem with an exact react-rail environment.

I'm going to invest a lot of time into React components later working on the app so I'll revisit this issue then.
